### ISSUE TITLE
répertoire des atlas produits

### ISSUE THREAD

**Issue by DonovanMaillard** [PnEcrins/GeoNature-atlas#101]
Penser à faire sur le github un répertoire des structures qui ont déployé l'atlas, et leurs adresses :) Ca peut donner des idées de naviguer sur tel ou tel atlas des autres structures, voir ce qui est modifiable, savoir comment etc.

**Comment by camillemonchicourt** [comment]
C'est déjà le cas sur la HOME du projet : https://github.com/PnEcrins/GeoNature-atlas
Pour le moment il n'y a que Biodiv'Ecrins, mais on ajoutera les autres au fur et à mesure quand il passeront en production.
