### ISSUE TITLE
FICHE TAXON - intégrer un graph altitudinal des observations

### ISSUE THREAD

**Issue by gildeluermoz** [PnEcrins/GeoNature-atlas#11]

**Comment by TheoLechemia** [comment]
Bug: les légendes disparaissent quand on redimensionne la page ...

**Comment by gildeluermoz** [comment]
J'ai eu le même soucis dans GeoNature :
Add a $(window).on('resize', ...) event handler then call the graphs redraw() function
http://stackoverflow.com/questions/35470089/how-to-resize-morris-js-chart-on-changes-to-container-dimensions

**Comment by gildeluermoz** [comment]
c'est quoi le soucis ici. Ce ticket est résolu non ?
Sinon, le fermer et en ouvrir un explicite ou le modifier pour qu'il le soit.

**Comment by camillemonchicourt** [comment]
Oui et même le problème de redimensionnement semble réglé !
