### ISSUE TITLE
Fiche "espèce suivante" / "espèce précédente"

### ISSUE THREAD

**Issue by sig-pnrnm** [PnEcrins/GeoNature-atlas#116]
Pour utiliser divers portails faunistiques, au premier rang duquel l'INPN, je trouve très pratique de naviguer d'une espèce à l'autre sans obligatoirement faire une nouvelle recherche.
Avoir 2 petits boutons (flèches) pour passer aux espèces (taxons) suivantes/précédentes (dans l'ordre taxonomique si possible, alphabétique sinon) serait pour moi très pratique.

Quelques exemples de portails qui le permettent : 
INPN > https://inpn.mnhn.fr/espece/cd_nom/608364 
Lepinet > http://www.lepinet.fr/especes/nation/lep/index.php?e=l&id=31730
Leps.it > http://www.leps.it/indexjs.htm?SpeciesPages/AnthoBelia.htm

Ces deux petites flèches ne nuiraient pas à l'ergonomie car très discrètes tout en ajoutant une fonctionnalité utile de navigation.

**Comment by camillemonchicourt** [comment]
Discuté sur https://github.com/PnEcrins/GeoNature-atlas/issues/82

**Comment by sig-pnrnm** [comment]
Merci pour le lien et désolé pour le doublon.

**Comment by camillemonchicourt** [comment]
Tes remarques sont complémentaires !
