### ISSUE TITLE
Duplication de l'image principale

### ISSUE THREAD

**Issue by gildeluermoz** [PnEcrins/GeoNature-atlas#118]
Il est actuellement possible de mettre plusieurs images principales dans la table ``taxonomie.t_medias`` de ``geonaturedb``. Du coup dans ``atlas.vm_medias`` de ``geonatureatlas`` un cd_ref peut avoir plusieurs images principales (``id_type = 1``).
Lorsqu'un refresh se fait sur ``atlas.vm_taxons_plus_observes`` la contrainte d'unicité sur cd_ref peut bloquer le rafraîchissement de la vue et donc de toute la transaction lors de l'exécution de  ``refreshallmaterializedviews ``.
En effet le sql de la vue  ``atlas.vm_taxons_plus_observes`` comporte une jointure sur le ``id_type = 1`` de ``atlas.vm_medias`` 

    
        SELECT count(*) AS nb_obs,
         obs.cd_ref,
         tax.lb_nom,
         tax.group2_inpn,
         tax.nom_vern,
         m.url,
         m.chemin,
         m.id_type
        FROM atlas.vm_observations obs
       JOIN atlas.vm_taxons tax ON tax.cd_ref = obs.cd_ref
       LEFT JOIN atlas.vm_medias m ON m.cd_ref = obs.cd_ref AND m.id_type = 1
       WHERE date_part('day'::text, obs.dateobs) >= date_part('day'::text, 'now'::text::date - 15) AND date_part('month'::text, obs.dateobs) = date_part('month'::text, 'now'::text::date - 15) OR date_part('day'::text, obs.dateobs) <= date_part('day'::text, 'now'::text::date + 15) AND date_part('month'::text, obs.dateobs) = date_part('day'::text, 'now'::text::date + 15)
      GROUP BY obs.cd_ref, tax.lb_nom, tax.nom_vern, m.url, m.chemin, tax.group2_inpn, m.id_type
      ORDER BY count(*) DESC
      LIMIT 12

**Comment by camillemonchicourt** [comment]
Ok alors peut etre a empecher au moment de la saisie dans TaxHub.

**Comment by gildeluermoz** [comment]
Je propose de forcer le comportement par un trigger en base (insert et update) : 
Si une image principale existe déjà, plutôt que de bloquer l'enregistrement, on remplace l'ancienne par la nouvelle (l'ancienne devient de type 2 = photo). On lève une notice qu'il est possible d'afficher en interface dans Taxhub.

**Comment by camillemonchicourt** [comment]
Ah oui bonne idée que de remplacer par la dernière et basculer la précédente en photo normale, c'est bien comme ça en effet.

**Comment by gildeluermoz** [comment]
Done : https://github.com/PnX-SI/TaxHub/commit/621ce79ea14e44b296648cf92b385b6cff582c6d
Merci de nettoyer les doublons sur le type 1 dans vos bases de données 

    SELECT count(*), cd_ref FROM atlas.vm_medias WHERE id_type = 1 ORDER BY DESC;

**Comment by gildeluermoz** [comment]
pour mettre à jour votre base GeoNature
https://github.com/PnX-SI/TaxHub/blob/develop/data/update1.2.0to1.3.0.sql
