### ISSUE TITLE
Condition de jointure à améliorer pour parer à la présence de caractères invisibles

### ISSUE THREAD

**Issue by mathieubossaert** [PnEcrins/GeoNature-atlas#124]
https://github.com/PnEcrins/GeoNature-atlas/blob/c94b8e67df0bc8552eb464b9505be26b7edacabf/main/modeles/repositories/vmTaxonsRepository.py#L46

```sql
JOIN atlas.bib_taxref_rangs bib_rang ON trim(tax.id_rang) = trim(bib_rang.id_rang)
```
Ou supprimer les caractères invisibles dans bib_rang.

**Comment by camillemonchicourt** [comment]
OK on n'avait pas ce cas mais c'est modifié et ça sera disponible dans la prochaine release.
