### ISSUE TITLE
Condition ternaire pour affichage du pluriel / singulier

### ISSUE THREAD

**Issue by Splendens** [PnEcrins/GeoNature-atlas#126]
Bonjour, 
Pour toutes les vues où il y a un affichage de mots pouvant être au singulier ou au pluriel, une condition ternaire permettrait d'éviter des fautes d'orthographe du style "1 commune**s**", "1 observation**s**"...

```
<li>
     <img id="picto" src="{{url_for('static', filename='images/church.png')}}" style="width"><br/>
     <b>{{communes|length}}</b><br/>
     {{ 'Communes' if communes|length > 1 else 'Commune' }}
</li>

```

**Comment by TheoLechemia** [comment]
Bonjour,
Merci pour la contribution. 
Si vous l'avez testé et que cela fonctionne, vous pouvez faire une pull-request. C'est plus simple pour nous d'intégrer toutes ces petites modifications ensuite.

Merci
