### ISSUE TITLE
Utiliser les vignettes générées par TaxHub

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature-atlas#129]
Actuellement dans les listes de taxons, la vignette affichée est en fait la photo_principale du taxon si elle existe. 
Du coup ce sont de grosses images qui sont chargées mais qui sont affichées très petites. Cela augmente considérablement le poids des pages des listes. 

La version 1.3.2 de TaxHub à venir intègre un mécanisme de génération à la volée de vignettes, stockées en dur au niveau de TaxHub lors de la première interrogation : https://github.com/PnX-SI/TaxHub/issues/108

Il reste donc à ajouter une fonctionnalité pour pouvoir utiliser ces vignettes dans GeoNature-atlas (au niveau des dernières observations sur HOME, des fiches Communes, Rangs et Groupes). 
Cette fonctionnalité doit être paramétrable dans le cas de ceux qui n'utilisent pas TaxHub.

**Comment by camillemonchicourt** [comment]
A affiner. Actuellement, que l'on fixe une largeur ou pas, l'image est déformée (à voir côté TaxHub).
Les tailles de redimensionnement sont à affiner aussi. 
Et pas sur que ce soit une bonne idée de redimensionner sur les fiches détails. Car ensuite on charge les grandes dans le slideshow, donc double chargement.

**Comment by camillemonchicourt** [comment]
Les déformations étaient liés à un probleme de notre TaxHub en python. 
On a migré notre TaxHub et c'est OK.

**Comment by gildeluermoz** [comment]
A noter au passage que la compatibilité python 2.7 n'est plus assurée, au moins pour cette fonctionnalité.

**Comment by camillemonchicourt** [comment]
Tu parles de la compatibilité Python de TaxHub là ? 
Pas de GN-atlas.

**Comment by gildeluermoz** [comment]
oui j'ai corrigé mon commentaire dans la foulé

**Comment by camillemonchicourt** [comment]
OK. Il ne reste plus qu'a ajuster les tailles des images redimensionnées dans GN-atlas.

**Comment by gildeluermoz** [comment]
Houps désolé, j'ai fermé le ticket par erreur.

**Comment by camillemonchicourt** [comment]
Les tailles des images ont été ajustées : https://github.com/PnEcrins/GeoNature-atlas/commit/3d2f50420472fa1111ff307d017700f5c691901f
