### ISSUE TITLE
Classe d'altitude - Créer une BIB

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature-atlas#13]
Créer une table des classes d'altitude, comme ça il est simple pour chacun de personnaliser ou rajouter des classes.
La VM boucle sur cette bib pour chaque taxon.

**Comment by camillemonchicourt** [comment]
Code côté BDD - https://github.com/PnEcrins/GeoNature-atlas/commit/1a7d101cd0e47a1025ff13e10aa21313e5b348ed

Et https://github.com/PnEcrins/GeoNature-atlas/commit/c93d2fa3b22e1009d490e87c409a0d4ac9a8748d

**Comment by gildeluermoz** [comment]
On a un soucis sur le fichier ``vmAltitudes.py`` dans``modeles/entities`` qui est une description de la vue ``vm_altitudes``. Je ne vois pas comment le rendre générique. Sauf à créer une tache qui le créé à partir du contenu de la vue.
On pourrait imaginer un fichier bash qui lance la fonction sql générant la vue à partir du contenu de ``bib_altitudes`` puis qui lance un fichier python qui génère l'entitie. C'est beau la généricité !

**Comment by camillemonchicourt** [comment]
Ouais ça fait chier de mettre en place encore une commande pour ça mais je capte le problème...
@amandine-sahl , une meilleure idée ? :-)

**Comment by camillemonchicourt** [comment]
Amandine : "Ce n'est pas obligé de déclarer les colonnes de la vue, vous pouvez utiliser une déclaration implicite de table".

**Comment by camillemonchicourt** [comment]
Il y a un exemple dans la classe route de taxref de TaxHub-api :
https://github.com/PnX-SI/TaxHub-api/blob/master/apptax/taxonomie/routestaxref.py

```Python
from sqlalchemy import create_engine, MetaData, Table

class GenericTable:
    def __init__(self, tableName, schemaName):
        engine = create_engine(init_app().config['SQLALCHEMY_DATABASE_URI'])
        meta = MetaData(bind=engine)
        meta.reflect(schema=schemaName, views=True)
        self.tableDef = meta.tables[tableName]
        self.columns = [column.name for column in self.tableDef.columns]

    def serialize(self, data):
        return serializeQuery(data, self.columns)

def serializeQuery( data, columnDef):
    rows = [
        {c['name'] : getattr(row, c['name']) for c in columnDef if getattr(row, c['name']) != None } for row in data
    ]
    return rows

tableTaxref = GenericTable('taxonomie.taxref', 'taxonomie') 
```

**Comment by gildeluermoz** [comment]
Tous est en place sur le modèle de la classe générique d'accès au modèle d'amandine : ee834b0a8ad8e2076d91e1273a2562e69f5eb5d3 et 0ea131940d09cec5cddc72844506e3f762e32e80

J'ai mis ça dans le répertoire modele/utils.py
+ simplification des imports.
