### ISSUE TITLE
Pouvoir afficher des pages spécifiques de façon générique

### ISSUE THREAD

**Issue by Splendens** [PnEcrins/GeoNature-atlas#131]
Bonjour, 

Pour mon atlas, j'ai besoin d'avoir des pages d'informations dédiées : "partenaires", collectivitée", etc. Suite au mail d'hier de @camillemonchicourt , j'ai développé un système de génération de pages spécifiques (dont présentation) de façon générique.

Il faut une table en BD pour les pages qu'on souhaite rajouté au site, et la sidebar est générée grâce à cette table. Il faut aussi rajouter le modèle / repository de t_pages + récupérer la variables "pages" dans  toutes les routes. 

J'ai également mis un paramètre AFFICHAGE_PAGES dans le config.py pour choisir d'afficher ces pages ou non. Mais je me demande si ce paramètre est vraiment utile ? Sachant que si, par défaut, la table ne contient que la page de présentation, il n'y aura pas d'autres pages tant qu'elles ne seront pas renseignées en bd... 

TABLE : 

`atlas.t_pages`
`( id_page integer PRIMARY KEY,`
`  route text, --utilisé pour généré l'url d'accès à la page`
`  picto text, --pour le picto dans la sidebar`
`  ordre integer, --pour l'ordre d'affichage des page dans la sidebar`
`  titre text --pour le data-original-title`
`)`

EXEMPLE POUR PRESENTATION : 

`1, 'presentation', 'question-sign', 1, 'Présentation de l'atlas'`

SIDEBAR :  

` {% if configuration.AFFICHAGE_PAGES %}`
`            {% for page in pages %}`
`                <a href="{{ page.route }}" data-toggle="tooltip" data-original-title="{{page.titre}}" data-placement="right">`
`                  <li class="sidebar-brand"><span class="glyphicon glyphicon-{{page.picto}}"></span></li>`
`                </a>`
`            {% endfor %}`
`          {% endif %}`

**Comment by camillemonchicourt** [comment]
Excellent ! Ça va apporter pas mal de possibilités à l'application. On pourra même modifier, renommer ou supprimer la page PRESENTATION, ce qui n'était pas possible actuellement. 
En effet le paramètre `AFFICHAGE_PAGES` n'est pas utile. Si on ne veut aucune page, il suffit alors de vider la table `t_pages`. 

Je me pose une question sur le CSS. Actuellement dans la page `PRESENTATION.HTML` on chargeait un fichier CSS spécifique : https://github.com/PnEcrins/GeoNature-atlas/blob/master/static/css/presentation.css
On aurait du coup intérêt à le renommer `page.css` pour clarifier et qu'il serve de bases réutilisable aux autres pages que chacun se créerait.

**Comment by Splendens** [comment]
Ah oui, ce serait plus cohérent !

**Comment by camillemonchicourt** [comment]
Voir le commit - https://github.com/Splendens/atlas_biodiv_pdl/commit/40aff2a2128d7907fe036b468927fc6be220149c

**Comment by amandine-sahl** [comment]
Les pages statiques sont maintenant configurables via le fichier de configuration. 

Je n'ai pas conservé l'idée d'avoir une table en base car je trouve qu'il faut dans la mesure du possible minimiser le stockage des paramètres d'affichages en base. Même si le débat reste ouvert

**Comment by camillemonchicourt** [comment]
OK oui c'est une bonne approche aussi.
Par contre sur ajoutes /static_page/ dans la route avant le nom de la page ?

Merci aussi pour le travail sur le fichier des routes et la definition d'une base_config commune à toutes les routes.

**Comment by camillemonchicourt** [comment]
OK donc le /static_page/ a été supprimé dans l'URL. 
Les routes aussi sont générées automatiquement en fonction des paramètres des pages. 
Excellent, on va pouvoir intégrer ça dans la RELEASE en cours. 

@Splendens, ça te va ?
Du coup Amandine a préféré gérer ça en conf plutôt qu'en base. Ça se discute mais les 2 solutions ont leurs avantages.

**Comment by Splendens** [comment]
Oui, ça marche aussi en conf. Par contre, ne gérer aucun paramétrage en BD ferme la porte à une interface d'administration web pour l'atlas. Mais c'est peut-être un point qui a déjà été discuté et écarté ?

**Comment by camillemonchicourt** [comment]
Oui j'avais pensé à cela. 
En effet, le choix a été fait d'utiliser TaxHub pour la gestion des infos relatives aux taxons (medias, description...). 
Du coup on n'a pas prévu d'admin de GN-atlas. 
Pas sur que pour les pages WEB cela soit pertinent. 

Mais ça se discute, à terme, ça peut être utile.

**Comment by camillemonchicourt** [comment]
Un autre avantage de ce qui a été fait est que les routes sont générées dynamiquement et qui'Amandine en a profité pour faire un bon ménage sur les appels de la configuration avec une conf de base de base pour toutes les routes et ce qui leir est spécifique à chacune.

**Comment by Splendens** [comment]
Oui, je viens d'éplucher ça ! C'est super ce petit nettoyage, merci @amandine-sahl  !  :+1: 

Pour l'administration, j'imaginais un truc un peu comme webobs, ou tous les paramètres sont stockés en BD, et l'utilisateur n'a pas besoin de "mettre les mains dans le code", avec des formulaires pour les choix de config, CMS pour les pages, ...

**Comment by camillemonchicourt** [comment]
Oui ça peut. 
Vu le profil des administrateurs et la quantité limitée de pages et de paramètres à manipuler, cela ne a pas paru essentiel, mais si quelqu'un est motivé pour mettre ça en place, avec plaisir !

**Comment by amandine-sahl** [comment]
A mon avis c'est plus difficile d'écrire une page statique que de modifier une config. D'où le choix qui a été fait.
