### ISSUE TITLE
Customisation de l'affichage des données ponctuelles sur la carte

### ISSUE THREAD

**Issue by amandine-sahl** [PnEcrins/GeoNature-atlas#133]
Exemple (CEN-LR)
![image](https://user-images.githubusercontent.com/3088650/36146896-7429f6ce-10b6-11e8-9a67-077f3f2d87ef.png)

**Comment by sig-pnrnm** [comment]
Pour les atlas qui ont choisi une restitution par mailles, il serait également utile de prévoir une costumisation selon le niveau de validation.
Mes collègues et moi pensions à un bouton de switch (on/off), pour tenir compte, ou non, des données non encore validées.
(en lien avec le [module de validation](https://github.com/PnX-SI/gn_module_validation/) )

**Comment by camillemonchicourt** [comment]
Actuellement l'idée est de pouvoir différencier l'affichage des points en fonction d'un champs de la BDD non prédéfini, en surcouchant le fonctionnement de base par défaut. 

En effet le CEN-LR a fait une customisation similaire mais en modifiant en dur l'application, ce qui rend sa mise à jour complexe : http://www.libellules-et-papillons-lr.org/atlas/

Le développement réalisé par le PnCevennes permet de faire cela de manière générique, en surcouchant sans modifier l'application en dur dans son cœur. 

Et d'utiliser cela de manière souple (pour la validation, la sensibilité ou autre). 

Les modifications apportées permettent : 
- D'ajoutant un champs dans la VM_ovservations sans avoir à modifier le code de GN-atlas
- De pouvoir définir le style d'affichage des points en fonction de la valeur de ce champs, en utilisant un fichier de surcouche javascript (https://github.com/PnEcrins/GeoNature-atlas/blob/80cfb89bf8e3571dfae5cb95ee113f2b94bf0b23/static/custom/maps.js.custom)

Pour les mailles, c'est une autre affaire, car une maille peut comporter des observations avec des valeurs diverses de ce champs. 
Mais on ajoute encore de la complexité et on se détourne de plus en plus d'un outil simple et facilement lisible. 

Déjà ajouter plusieurs types de points ça complexifie la lecture et je ne suis pas sur que tout le monde comprenne ce qu'est une donnée validée ou non. 
Mais pourquoi pas, c'est ce qu'a fait le CEN-LR uniquement quand on passe à l'affichage ponctuel : http://www.libellules-et-papillons-lr.org/atlas/espece/53741

Avec cette nouvelle fonctionnalité, ils pourront le faire de manière plus générique, sans modifier le cœur de GN-atlas. 

Si on veut l'ajouter au niveau des mailles, en effet, il faut ajouter un switch. C'est faisable. 

Alalalala, les données sensibles et la validation des données, les 2 éternels sujets qui amènent toujours à des usines à gaz et ont donc bloqué le partage et la diffusion des données de la biodiversité depuis des années et donc l'asphyxie à petit feu. :-)

Y aurait-il moins d'experts dans les autres domaines ? :-)

**Comment by sig-pnrnm** [comment]
> Y aurait-il moins d'experts dans les autres domaines ? :-)

Je ne comprends pas ce que tu veux dire ?

> les données sensibles et la validation des données, les 2 éternels sujets qui amènent toujours à des usines à gaz

C'est clair que ça complique l'affaire.
Mais il ne faut pas nier l'importance de ces 2 thèmes : 
- il y a **réellement** des données sensibles, qu'il faut pouvoir masquer pour ne pas mettre en danger certaines espèces (ex. : j'ai des données de nidification de Cigogne noire que je n'intègre pas actuellement)
- on a **tous**, il ne faut pas se leurrer, des données douteuses dans nos bases. Le travail de validation donne une réelle plu-value aux données

Et il y a nécessairement un moyen, pour l'utilisateur final, pour que ce ne soit pas une usine à gaz !
(mais c'est peut-être hors sujet en ce qui concerne l'issue en question ;) )

**Comment by camillemonchicourt** [comment]
Oui mais ces 2 sujets bloquent toute la diffusion des données depuis des années pour quelques % des données concernées. 
Et le préjudice à la biodiversité est bien plus lourd que le gain pour celle-ci. 

Mais bon on va pas refaire le débat ici, on garde ça pour le workshop GeoNature. :-)

**Comment by camillemonchicourt** [comment]
La surcouche est à faire dans ``static/custom/maps-custom.js``.

Exemple de surcouche javascript pour afficher une couleur de point en fonction de la sensibilité des observations, après avoir ajouté un champs contenant l'info dans ``atlas.vm_observations``

``` js
// Paramètres de customisation d'affichage de la carte

// Fonction style d'affichage des points dans la fiche espèce
var pointDisplayOptionsFicheEspece = pointDisplayOptionsFicheCommuneHome = function(feature) {
    return {
      fillColor: (feature.properties.id_nomenclature_niv_precis > 0 ? "#3A9D23" : "#3388ff"),
      color:(feature.properties.id_nomenclature_niv_precis > 0 ? "#3A9D23" : "#3388ff")
    }
  };


// Légende des points dans la fiche espèce
var divLegendeFicheEspece = divLegendeFicheCommuneHome = '\
    <p><div>\
        <i class="circle" style="border: 3px solid #3A9D23; border-radius: 50%; width: 20px; height: 20px;"></i>Dégradées\
    </div></p>\
    <p><div>\
        <i class="circle" style="border: 3px solid #3388ff; border-radius: 50%; width: 20px; height: 20px;"></i>Non dégradées\
    </div></p>\
';
```
