### ISSUE TITLE
Configuration de l'info patrimoniale

### ISSUE THREAD

**Issue by amandine-sahl** [PnEcrins/GeoNature-atlas#134]
- [x] Selectionner l'id de l'attribut concerné (à l'heure d'aujourd'hui en dur dans le code)
- [x] Spécification des valeurs possibles et de l'icone associé
- [x] Customiser le message d'information

**Comment by amandine-sahl** [comment]
Selectionner l'id de l'attribut concerné (à l'heure d'aujourd'hui en dur dans le code) -> Ce fait via les vues matérialisées

**Comment by camillemonchicourt** [comment]
Cela permet de renommer le nom affiché de la colonne (même si ça se base toujours sur le champs nommé Patrimonial) et de configurer des pictos en fonction des valeurs de ce champs : https://github.com/PnEcrins/GeoNature-atlas/blob/c27f15af3879d6f2664d0e3220dd32c52e5145df/main/configuration/config.py.sample#L165-L177

Exemple de résultat en renommant la colonne ENJEUX avec 3 valeurs possibles : 

![inidgeejhhgicnmj](https://user-images.githubusercontent.com/4418840/36230249-1aeb7ad6-11da-11e8-9a57-c2eb30eabd67.png)
