### ISSUE TITLE
Erreur dans le fichier grant.sql

### ISSUE THREAD

**Issue by lpofredc** [PnEcrins/GeoNature-atlas#137]
Une erreur s'est glissée dans le fichier data/grant.sql, ligne 36:

```sql
GRANT SELECT ON TABLE atlas.bib_altitudes TO TO my_reader_user;
```
`TO` est en double ce qui induit une erreur d'attribution du droit `SELECT` et empêche l'affichage de la page de synthèse de l'espèce par manque d'authorisation.

**Comment by camillemonchicourt** [comment]
Bien vu, cela a été corrigé et pas mal de choses aussi au niveau de l'installation sans GeoNature : https://github.com/PnEcrins/GeoNature-atlas/commits/develop

Une version corrective sortira prochainement avec ces différentes corrections. 

Merci.
