### ISSUE TITLE
Installation taxonomie - Fixer version

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature-atlas#138]
Si le paramètre proposant d'installer le schéma taxonomie est à TRUE (https://github.com/PnEcrins/GeoNature-atlas/blob/master/main/configuration/settings.ini.sample#L44-L45), alors il faudrait un paramètre indiquant la version de TaxHub à utiliser pour ne pas prendre les scripts dans le master de TaxHub. 
Avant chaque release de GN-atlas on modifierait éventuellement la valeur par défaut de ce paramètre.

**Comment by TheoLechemia** [comment]
Fait: d4a500145f1a06bf852dd0511272895c5d2fbb63

**Comment by camillemonchicourt** [comment]
Ce commit c'est autre chose.
Là le numero de version de TaxHub est en dur dans le install_db.sh
C'est peut etre pas plus mal comme ça mais il faudra penser à le changer si on veut faire evoluer la version de TaxHub.

**Comment by TheoLechemia** [comment]
Oups voila le bon commit: **https://github.com/PnEcrins/GeoNature-atlas/commit/70d37af89b66ed9d9331dee5fe52e94f5fb33f3e**
Je rajoute un paramètre dans le settings.ini en spécifiant les versions compatibles.
