### ISSUE TITLE
FICHE TAXON - nbre d'observations

### ISSUE THREAD

**Issue by gildeluermoz** [PnEcrins/GeoNature-atlas#16]
Remplacer : Nombre d'observation sur le parc: n
par
n observation(s)

D'autre part il y a une incohérence entre le nbre d'obs en haut de la fiche et le résultat dans le slider (même si on affiche toutes les années). Test réalisé avec "Boloria graeca"

Après avoir diagnostiquer la source de l'incohérence, se poser la question : faut-il conserver l'information au 2 endroits ?

**Comment by camillemonchicourt** [comment]
A terme, Je pensai ne garder que le compteur dynamique en bas en effet

**Comment by camillemonchicourt** [comment]
L'incohérence est du au fait que le slider commence à une année fixe (1973 dans notre cas), alors que pour BOLORIA GRAECA, il y a des observations avant 1973...
On investigue un système qui calcule les années min et max pour chaque taxon de manière dynamique. https://github.com/PnEcrins/GeoNature-atlas/issues/8

**Comment by TheoLechemia** [comment]
Dernier commit: calcul dynamique de l'observation la plus ancienne pour chaque taxon.
Un peu lourd à faire côté client, peut-être intéressant de le générer directement dans la vue.

**Comment by gildeluermoz** [comment]
A voir aussi s'il ne serait pas plus simple et plus rapide de lancer une simple requête avec un max(extract_year(dateobs)) depuis python. Sinon je regarde s'il est possible de stocker ça dans la vue taxons sans trop l'alourdir.

**Comment by camillemonchicourt** [comment]
Nombre d'obs total ajouté dans vm_taxons et utilisé dans les fiches espèces.
