### ISSUE TITLE
Source librairie Leaflet Markercluster ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature-atlas#17]
Je me demande si il faut la prendre directement chez MapBox comme actuellement https://github.com/PnEcrins/GeoNature-atlas/blob/master/templates/ficheEspece.html#L35-L37
Ou si il faut prendre directement le plugin chez Leaflet - https://github.com/Leaflet/Leaflet.markercluster

C'est peut-être plus sur de l'embarquer comme dans le projet du PnC - https://github.com/PnCevennes/projet_suivi/tree/master/web/js/lib

Ils embarquent le JS et le CSS - https://github.com/PnCevennes/projet_suivi/blob/master/web/suivi.html#L18-L34

**Comment by TheoLechemia** [comment]
C'est fait
