### ISSUE TITLE
Leaflet Fullscreen

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature-atlas#18]
Ce bouton est top aussi et serait bien à ajouter sur la carte. 

https://github.com/Leaflet/Leaflet.fullscreen

Proposé en lien CDN chez MapBox (comme pour MarkerCluster - https://github.com/PnEcrins/GeoNature-atlas/issues/17)

Ici je vois qu'il le prend directement avec un lien vers un autre projet - https://github.com/makinacorpus/django-mapentity/tree/master/mapentity/static/mapentity

**Comment by camillemonchicourt** [comment]
Ici ils le prennent sur le dépôt de Leaflet.... https://github.com/makinacorpus/Geotrek-rando/blob/master/package.json#L61

**Comment by TheoLechemia** [comment]
Fait. Je l'ai pris sur le dépôt leaflet
