### ISSUE TITLE
Calcul de l'observation la plus ancienne dans la vue ?

### ISSUE THREAD

**Issue by TheoLechemia** [PnEcrins/GeoNature-atlas#20]
Le calcul de l'observation la plus ancienne côté client est un peu lourde. A voir si c'est pas plus performant de la calculer directement dans la vue.

**Comment by camillemonchicourt** [comment]
Oui en effet ! 
Lié à https://github.com/PnEcrins/GeoNature-atlas/issues/8

**Comment by camillemonchicourt** [comment]
Vue complétée avec l'altitude ici - https://github.com/PnEcrins/GeoNature-atlas/commit/1a7d101cd0e47a1025ff13e10aa21313e5b348ed
