### ISSUE TITLE
HOME - Carte des 100 dernières observations

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature-atlas#30]
- Supprimer le nom des observateurs
- Mettre le nombre d'observations en paramètres
- Ajouter un lien vers la fiche espèce

**Comment by TheoLechemia** [comment]
Done: 
Commit: https://github.com/PnEcrins/GeoNature-atlas/commit/00f80368e492a6ad82e75277152787d220215245
