### ISSUE TITLE
L'autocomplétion de la recherche par taxon ne fonctionne plus

### ISSUE THREAD

**Issue by gildeluermoz** [PnEcrins/GeoNature-atlas#34]

**Comment by TheoLechemia** [comment]
Je m'en suis rendu compte ce matin avant de passer la soutenance ...
On a déjà eu ce problème, et le lendemain c'était résolu.. je sais pas d'ou ça vient puisque je n'ai rien touché depuis hier soir, et ça marchait...
La console du debugger affiche ça :
` Failed to load resource: the server responded with a status of 404 (Not Found)`

Je regarde demain matin

**Comment by gildeluermoz** [comment]
Pistes : 
le nombre de connexions simultanées autorisées sur le serveur postgres. L'orm ferme t-il les connexions sur la base ? Le pb peut venir des connexions sur la base distantes avec le FDW.
Tenter un restart du postgres local et/ou distant
Regarder les logs postgres aussi

**Comment by gildeluermoz** [comment]
``Failed to load resource`` Il faudrait identifier de quelle ressource il s'agit et pourquoi un 404.
Peut-être augmenter le niveau de débug d'apache temporairement pour qu'il soit plus explicite.

**Comment by TheoLechemia** [comment]
Le problème venait du JavaScript, les deux formulaires de recherche se chevauchaient.
