### ISSUE TITLE
LISTE TAXONS - RECURSIVITE - afficher la taxonomie supra

### ISSUE THREAD

**Issue by gildeluermoz** [PnEcrins/GeoNature-atlas#37]
Comme dans une fiche espèce, lorsque l'on est sur la liste des taxons d'un genre ou d'une famille par exemple, il faudrait pouvoir cliquer sur un des niveaux taxonomiques supérieurs pour avoir la liste des taxons observés pour ce niveau. Actuellement pour faire cela, il faut repasser par la fiche espèce.

**Comment by TheoLechemia** [comment]
Fait
