### ISSUE TITLE
Récursivité taxonomie ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature-atlas#4]
Voir les développements de l'API dans le cadre du stage au CEN LR pour mettre en place un atlas basé sur les données présentes dans SiCen : 
* https://github.com/CENSIG/api
* https://github.com/CENSIG/client-interface
* https://github.com/CENSIG/client-interface-components

Précisions @mathieubossaert :

> Pour faire court, nous sommes partis du postulat de départ que toutes les données d'observation stockées dans SiCen sont rattachées à un référentiel taxonomique, qui a une structure arborescente. 
> 
> Nous disposons dans nos base de données des outils pour interroger et explorer ce type de structure de données (récursivité). Ainsi, en tout nœud du référentiel, nous pouvons faire la synthèse sur l'ensemble des fils du nœud, sans connaitre a priori la profondeur de l'arbre.
> 
> Et donc afficher une page de synthèse pour n'importe quel taxon :
> * /ordre des lépidioptères : http://xxxxx/atlas/papillons/
> * /famille des geometridae : http://xxxxx/atlas/papillons/185259/
> * /espèce pyronia tithonus : http://xxxxx/atlas/papillons/608405/

**Comment by camillemonchicourt** [comment]
@mathieubossaert, en discutant avec les chargés de mission ici, il leur semble intéressant et nécessaire d'agglomérer jusqu'à l'espèce, pour que la fiche d'une espèce n'oublie pas les éventuelles observations faites au niveau des sous-espèces. 
Par contre au niveau supérieur, ils préfèrent afficher des listes d'espèces plutôt que d'agglomérer des données qui pourraient du coup avoir peu de sens selon le niveau et le groupe. D'autant plus que l'on traite de la même manière de la flore et de la faune. 

Si possible aussi, sur la fiche d'une espèce, faire afficher la liste des sous-espèces qui ont au moins une observation.

**Comment by camillemonchicourt** [comment]
@amandine-sahl, un avis ?

**Comment by mathieubossaert** [comment]
Salut Camille, 

je n'ai pas pris le temps de vous répondre mais j'ai bien testé l'appli. C'est un super boulot ! 
Avoir un élément de navigation dans la taxonomie serait top (taxons voisins / enfants / parents par exemple) 

Concernant l'agrégation au dessus de l'espèce, je pense que c'est intéressant jusqu'au genre, mais qu'au dessus en effet ça n'a plus trop de sens (sauf peut-être le nombre d'obs mais bof) 
Pour le genre ça l'ai parce qu'on a beaucoup d'espèces proches mais aussi beaucoup de données pour lesquelles l'observateur n'a pas pu aller plus loin dans la détermination. 
Et donc, pour ces différents niveaux (genre et espèce) , présenter la listes des taxons inférieurs pour lesquels on a des données. 

Mathieu 


Mathieu BOSSAERT 
-- 
Responsable du système d'information (http://si.cenlr.org) 
ligne directe : 04 67 29 90 65 

Membre de la Fédération des Conservatoires d'espaces naturels www.reseau-cen.org 
Venir nous voir 
Immeuble le Thèbes - 26 Allées de Mycènes - 34000 Montpellier 

----- Mail original -----

De: "Camille Monchicourt" <notifications@github.com> 
À: "PnEcrins/GeoNature-atlas" <GeoNature-atlas@noreply.github.com> 
Cc: "mathieubossaert" <mathieu.bossaert@cenlr.org>, "Mention" <mention@noreply.github.com> 
Envoyé: Lundi 27 Juin 2016 12:30:51 
Objet: Re: [PnEcrins/GeoNature-atlas] Récursivité taxonomie ? (#4) 


@mathieubossaert , en discutant avec les chargés de mission ici, il leur semble intéressant et nécessaire d'agglomérer jusqu'à l'espèce, pour que la fiche d'une espèce n'oublie pas les éventuelles observations faites au niveau des sous-espèces. 
Par contre au niveau supérieur, ils préfèrent afficher des listes d'espèces plutôt que d'agglomérer des données qui pourraient du coup avoir peu de sens selon le niveau et le groupe. D'autant plus que l'on traite de la même manière de la flore et de la faune. 
Si possible aussi, sur la fiche d'une espèce, faire afficher la liste des sous-espèces qui ont au moins une observation.

**Comment by camillemonchicourt** [comment]
Requêtes du CEN-LR pour alimenter l'API à partir des données dans SICEN : 

Voici la requête de parcours des obs (ici pour la famille des aeshnides : cd_ref = 185359)

```SQL
SELECT cd_taxsup, cd_nom, nom_vern, lb_nom, rang, ordre, phylum, classe, famille, observations, especes, communes, observateurs
                FROM (
                    WITH RECURSIVE descendants(cd_nom, cd_taxsup, cd_ref, info) AS (
                          SELECT cd_nom, cd_taxsup, cd_ref, array[cd_nom, cd_taxsup, ordre, phylum, famille, classe, nom_vern, lb_nom, rang] as info
                          FROM inpn.taxref_v8
                         WHERE cd_nom = '185359'
      
                        UNION ALL

                          SELECT e.cd_nom, e.cd_taxsup, e.cd_ref, info
                          FROM descendants AS ss
                         JOIN inpn.taxref_v8 AS e
                          ON e.cd_taxsup = ss.cd_nom
                    )

                    SELECT
                        info[1] as cd_nom,
                        info[8] as lb_nom,
                        info[2] as cd_taxsup,
                        info[3] as ordre,
                        info[4] as phylum,
                        info[5] as famille,
                        info[6] as classe,
                        info[7] as nom_vern,
                        info[9] as rang,
                        count(id_obs) as observations,
                        count(distinct code_insee) as communes,
                        count(distinct observateur) as observateurs,
                        count(distinct o.cd_nom) as especes
                    FROM descendants ss
                    JOIN inpn.taxref_v8 i
                    ON i.cd_ref = ss.cd_ref
                    LEFT JOIN saisie.saisie_observation o
                    ON i.cd_nom = o.cd_nom
                    WHERE i.cd_ref = ss.cd_nom
                    group by info[1], info[2], info[3], info[4], info[5], info[6], info[7], info[8], info[9]
) as infos
```

Et là la génération du geojson des mailles pour le même taxon :

```
SELECT features FROM (
                WITH RECURSIVE ancetres as  (

                    SELECT cd_taxsup, cd_nom, cd_ref as aïeul, lb_nom
                    FROM inpn.taxref_v8
                    where cd_nom = '185359'

                    UNION

                    SELECT syn.cd_taxsup, syn.cd_nom, syn.cd_ref AS aïeul, syn.lb_nom
                    FROM inpn.taxref_v8 tax join inpn.taxref_v8 syn USING(cd_ref)
                    where tax.cd_nom = '185359'

                    UNION

                    SELECT tax.cd_taxsup, tax.cd_nom, f.aïeul, f.lb_nom
                    FROM inpn.taxref_v8 tax
                    JOIN ancetres f
                    ON tax.cd_taxsup = f.cd_nom

            ), grid as (
                 select distinct g.geometrie
                 from export.grille_10km_l93 g
                 join ign_geofla.commune c
                 on st_intersects(c.geometrie, g.geometrie)
                 where code_reg = '91'
                 --group by g.geometrie

            ), feature as (

                SELECT 'Feature' AS type,
                row_to_json((SELECT ct FROM (SELECT count(id_obs) AS nombres) AS ct)) AS properties,
                cast(ST_AsGeoJson(g.geometrie, 4326) as json) AS geometry
                FROM grid g
                LEFT JOIN saisie.saisie_observation obs ON st_intersects(obs.geometrie,g.geometrie)
                JOIN ancetres a ON a.cd_nom = obs.cd_nom
                group by g.geometrie
            )

            SELECT array_to_json(array_agg(feature)) as features
            from feature
) as geojson
```

Les autres requêtes, par exemple pour lister toutes les photos d'un taxon et de ses descendant, les taxons parents et enfant (navigation) sont décrites ici :

https://github.com/CENSIG/api/blob/10816bc2b8e774b208145ad0d5ea7001a64b8e34/conf/META-INF/ebean-orm.xml

Doc WITH RECURSIVE - http://docs.postgresql.fr/9.4/queries-with.html

**Comment by mathieubossaert** [comment]
Nous n'avons pas pu utiliser les CTE sur l'ensemble de la requête car l'ORM retourne une erreur si elle ne commence pas par par SELECT... d'où le SELECT FROM () as sous-requete final. 

Le calcul prend ici moins de 500 ms sur une BDD de 190000 obs 


Mathieu BOSSAERT 
-- 
Responsable du système d'information (http://si.cenlr.org) 
ligne directe : 04 67 29 90 65 

Membre de la Fédération des Conservatoires d'espaces naturels www.reseau-cen.org 
Venir nous voir 
Immeuble le Thèbes - 26 Allées de Mycènes - 34000 Montpellier 

----- Mail original -----

De: "Camille Monchicourt" <notifications@github.com> 
À: "PnEcrins/GeoNature-atlas" <GeoNature-atlas@noreply.github.com> 
Cc: "mathieubossaert" <mathieu.bossaert@cenlr.org>, "Mention" <mention@noreply.github.com> 
Envoyé: Mardi 28 Juin 2016 11:06:50 
Objet: Re: [PnEcrins/GeoNature-atlas] Récursivité taxonomie ? (#4) 


Requêtes du CEN-LR pour alimenter l'API à partir des données dans SICEN : 
Voici la requête de parcours des obs (ici pour la famille des aeshnides : cd_ref = 185359) 
SELECT cd_taxsup, cd_nom, nom_vern, lb_nom, rang, ordre, phylum, classe, famille, observations, especes, communes, observateurs FROM (
                    WITH RECURSIVE descendants(cd_nom, cd_taxsup, cd_ref, info) AS ( SELECT cd_nom, cd_taxsup, cd_ref, array[cd_nom, cd_taxsup, ordre, phylum, famille, classe, nom_vern, lb_nom, rang] as info FROM inpn . taxref_v8 WHERE cd_nom = ' 185359 ' UNION ALL SELECT e . cd_nom , e . cd_taxsup , e . cd_ref , info FROM descendants AS ss JOIN inpn . taxref_v8 AS e ON e . cd_taxsup = ss . cd_nom ) SELECT info[ 1 ] as cd_nom,
                        info[ 8 ] as lb_nom,
                        info[ 2 ] as cd_taxsup,
                        info[ 3 ] as ordre,
                        info[ 4 ] as phylum,
                        info[ 5 ] as famille,
                        info[ 6 ] as classe,
                        info[ 7 ] as nom_vern,
                        info[ 9 ] as rang, count (id_obs) as observations, count (distinct code_insee) as communes, count (distinct observateur) as observateurs, count (distinct o . cd_nom ) as especes FROM descendants ss JOIN inpn . taxref_v8 i ON i . cd_ref = ss . cd_ref LEFT JOIN saisie . saisie_observation o ON i . cd_nom = o . cd_nom WHERE i . cd_ref = ss . cd_nom group by info[ 1 ], info[ 2 ], info[ 3 ], info[ 4 ], info[ 5 ], info[ 6 ], info[ 7 ], info[ 8 ], info[ 9 ]
) as infos 
Et là la génération du geojson des mailles pour le même taxon : SELECT features FROM (
                WITH RECURSIVE ancetres as  (

                    SELECT cd_taxsup, cd_nom, cd_ref as aïeul, lb_nom
                    FROM inpn.taxref_v8
                    where cd_nom = '185359'

                    UNION

                    SELECT syn.cd_taxsup, syn.cd_nom, syn.cd_ref AS aïeul, syn.lb_nom
                    FROM inpn.taxref_v8 tax join inpn.taxref_v8 syn USING(cd_ref)
                    where tax.cd_nom = '185359'

                    UNION

                    SELECT tax.cd_taxsup, tax.cd_nom, f.aïeul, f.lb_nom
                    FROM inpn.taxref_v8 tax
                    JOIN ancetres f
                    ON tax.cd_taxsup = f.cd_nom

            ), grid as (
                 select distinct g.geometrie
                 from export.grille_10km_l93 g
                 join ign_geofla.commune c
                 on st_intersects(c.geometrie, g.geometrie)
                 where code_reg = '91'
                 --group by g.geometrie

            ), feature as (

                SELECT 'Feature' AS type,
                row_to_json((SELECT ct FROM (SELECT count(id_obs) AS nombres) AS ct)) AS properties,
                cast(ST_AsGeoJson(g.geometrie, 4326) as json) AS geometry
                FROM grid g
                LEFT JOIN saisie.saisie_observation obs ON st_intersects(obs.geometrie,g.geometrie)
                JOIN ancetres a ON a.cd_nom = obs.cd_nom
                group by g.geometrie
            )

            SELECT array_to_json(array_agg(feature)) as features
            from feature
) as geojson 
Les autres requêtes, par exemple pour lister toutes les photos d'un taxon et de ses descendant, les taxons parents et enfant (navigation) sont décrites ici : 
https://github.com/CENSIG/api/blob/10816bc2b8e774b208145ad0d5ea7001a64b8e34/conf/META-INF/ebean-orm.xml 
Doc WITH RECURSIVE - http://docs.postgresql.fr/9.4/queries-with.html

**Comment by gildeluermoz** [comment]
Première adaptation à l'atlas
    ::

    SELECT cd_taxsup, cd_nom, nom_vern, lb_nom, rang, ordre, phylum, classe, famille, observations, especes, communes, observateurs
                FROM (
                    WITH RECURSIVE descendants(cd_nom, cd_taxsup, cd_ref, info) AS (
                          SELECT cd_nom, cd_taxsup, cd_ref, array[cd_nom::text, cd_taxsup::text, ordre, phylum, famille, classe, nom_vern, lb_nom, id_rang] as info
                          FROM taxonomie.taxref
                         WHERE cd_nom = '186233'

                        UNION ALL

                          SELECT e.cd_nom, e.cd_taxsup, e.cd_ref, info
                          FROM descendants AS ss
                         JOIN taxonomie.taxref AS e
                          ON e.cd_taxsup = ss.cd_nom
                    )

                    SELECT
                        info[1] as cd_nom,
                        info[8] as lb_nom,
                        info[2] as cd_taxsup,
                        info[3] as ordre,
                        info[4] as phylum,
                        info[5] as famille,
                        info[6] as classe,
                        info[7] as nom_vern,
                        info[9] as rang,
                        count(id_synthese) as observations,
                        count(distinct insee) as communes,
                        count(distinct observateurs) as observateurs,
                        count(distinct o.cd_ref) as especes
                        --o.cd_ref as especes
                    FROM descendants ss
                    JOIN taxonomie.taxref i
                    ON i.cd_ref = ss.cd_ref
                    LEFT JOIN atlas.vm_observations o
                    ON i.cd_nom = o.cd_ref
                    WHERE i.cd_ref = ss.cd_nom
                    group by info[1], info[2], info[3], info[4], info[5], info[6], info[7], info[8], info[9]--, o.cd_ref
    ) as infos

**Comment by camillemonchicourt** [comment]
Fonctions intégrées dans la BDD - https://github.com/PnEcrins/GeoNature-atlas/commit/b3e77f1f6b8ce7f58846452e6e85796e64a989b7

**Comment by TheoLechemia** [comment]
Utilisation de la bib_taxref_rang suivante qui permet de gérer la généricité d'affichage des templates Fiche vs Listes

![rang-taxonomique-tri](https://cloud.githubusercontent.com/assets/15265745/16759938/bae1502e-4819-11e6-92a9-6be9451b2123.png)

**Comment by camillemonchicourt** [comment]
La question de la récursivité a bien avancé. 
A partir de n'importe quel CD_REF, on peut retrouver tout ce qu'il y a au-dessus et en dessous. 
Du coup les informations relatives à une fiche espèce, intégreront aussi toutes les éventuelles observations faites sur ses sous-espèces, variétés...
Pour les rangs supérieurs, il est possible d'accéder à la liste de tous les taxons observés d'un ordre, famille, genre....
Et cerise sur la gâteau pour @mathieubossaert, un paramètre permet de choisir à partir de quel rang on passe en mode fiche ou liste. Du coup on peut afficher des listes jusqu'au genre puis des fiches à partir du rang espèce, tandis que d'autres pourront faire afficher des fiches dès le rang GENRE.

**Comment by mathieubossaert** [comment]
Great ! 

Super boulot. Hâte de déployer tout ça ;-) 

Mathieu 


Mathieu BOSSAERT 
-- 
Responsable du système d'information (http://si.cenlr.org) 
ligne directe : 04 67 29 90 65 

Membre de la Fédération des Conservatoires d'espaces naturels www.reseau-cen.org 
Venir nous voir 
Immeuble le Thèbes - 26 Allées de Mycènes - 34000 Montpellier 

----- Mail original -----

De: "Camille Monchicourt" <notifications@github.com> 
À: "PnEcrins/GeoNature-atlas" <GeoNature-atlas@noreply.github.com> 
Cc: "mathieubossaert" <mathieu.bossaert@cenlr.org>, "Mention" <mention@noreply.github.com> 
Envoyé: Mardi 12 Juillet 2016 10:22:03 
Objet: Re: [PnEcrins/GeoNature-atlas] Récursivité taxonomie ? (#4) 


La question de la récursivité a bien avancé. 
A partir de n'importe quel CD_REF, on peut retrouver tout ce qu'il y a au-dessus et en dessous. 
Du coup les informations relatives à une fiche espèce, intégreront aussi toutes les éventuelles observations faites sur ses sous-espèces, variétés... 
Pour les rangs supérieurs, il est possible d'accéder à la liste de tous les taxons observés d'un ordre, famille, genre.... 
Et cerise sur la gâteau pour @mathieubossaert , un paramètre permet de choisir à partir de quel rang on passe en mode fiche ou liste. Du coup on peut afficher des listes jusqu'au genre puis des fiches à partir du rang espèce, tandis que d'autres pourront faire afficher des fiches dès le rang GENRE.
