### ISSUE TITLE
Ne pas couper les mailles

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature-atlas#40]
Les mailles en bordure du territoire ne devraient pas être découpées, une maille doit toujours rester complète. 
Donc prendre toutes les mailles dans le territoire et intersectes par le territoire mais ne pas couper celles en bordure

**Comment by TheoLechemia** [comment]
C'est en cours !

**Comment by gildeluermoz** [comment]
Plonge dans la maille Sardaigne...
On s'occupe du reste ;-)

**Comment by TheoLechemia** [comment]
Fix
