### ISSUE TITLE
FICHE ESPECE - Agglomeration sous-espèces et médias

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature-atlas#42]
Quand on est sur une fiche ESPECE qui a des obs faites au niveau de ses SOUS-ESPECES (ou variétés...), les observations sont agglomérées ainsi que les photos.
Mais actuellement, il liste tous les medias dans la galerie photo, pas seulement ceux de type PHOTO.

**Comment by TheoLechemia** [comment]
Fix
