### ISSUE TITLE
Champs pour chaque taxon

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature-atlas#5]
**Infos calculées automatiquement pour chaque espèce :**

- Nom + Taxonomie + Liens INPN
- Carte de répartition des observations (navigable avec affichage par maille quand on visualise l'ensemble du territoire puis bascule sur les observations sous forme de points clusterisés à partir d'un certain zoom)
- Répartitions altitudinale
- Répartitions communales
- Répartitions par massif/secteur/unité géographique
- Périodes d’observation (phénologie)
- Statuts
- Observateurs

**Infos saisies sur chaque espèce (dans TaxHub) :**

- Description
- Commentaire libre agent
- Répartition / Distribution (régions)
- Habitats/Milieux (liste prédéfinie)
- Galerie photos
- Autres médias (audio, video)
- Liens vers article, PDF...

**Comment by mathieubossaert** [comment]
Salut Camille, hâte de pouvoir tester ça sur la base papillons-libellules LRMP mais il va me falloir un peu de temps d'appropriation de ces deux outils.

**Comment by camillemonchicourt** [comment]
Oui, pour le moment, il se base sur les observations présentes dans la synthèse GeoNature mais étant donné que l'atlas attaquera une vue, nous allons faire en sorte que celle-ci puisse être alimentée par une autre BDD que GeoNature. 

On en recause.

**Comment by mathieubossaert** [comment]
Super, potentiellement quelques CEN utilisateurs ;-)

**Comment by camillemonchicourt** [comment]
A suivre, on va voir jusqu'où on arrive dans le temps imparti.

**Comment by camillemonchicourt** [comment]
Proposition Damien : 

- Afficher la date de la dernière observation de l'espèce
- Un graph sur le nbs de données par année pour un taxon (cela mettrai en évidence l’augmentation ou la diminution des contacts avec celui-ci)

Gil parle aussi de la date de première observation.

**Comment by mathieubossaert** [comment]
Envisager plutôt l'année de première obs qui sera souvent une donnée biblio imprécise. 


Mathieu BOSSAERT 
-- 
Responsable du système d'information (http://si.cenlr.org) 
ligne directe : 04 67 29 90 65 

Membre de la Fédération des Conservatoires d'espaces naturels www.reseau-cen.org 
Venir nous voir 
Immeuble le Thèbes - 26 Allées de Mycènes - 34000 Montpellier 

----- Mail original -----

De: "Camille Monchicourt" <notifications@github.com> 
À: "PnEcrins/GeoNature-atlas" <GeoNature-atlas@noreply.github.com> 
Cc: "mathieubossaert" <mathieu.bossaert@cenlr.org>, "Comment" <comment@noreply.github.com> 
Envoyé: Lundi 27 Juin 2016 15:46:10 
Objet: Re: [PnEcrins/GeoNature-atlas] Champs pour chaque taxon (#5) 


Proposition Damien : 

    * Afficher la date de la dernière observation de l'espèce 
    * Un graph sur le nbs de données par année pour un taxon (cela mettrai en évidence l’augmentation ou la diminution des contacts avec celui-ci) 

Gil parle aussi de la date de première observation.

**Comment by camillemonchicourt** [comment]
Oui en effet. Actuellement cette info est déjà présente avec le petit curseur présent sur la carte qui commence à l'année de la première observation mais on pourrait aussi mettre plus en évidence cette info en la mentionnant dans la fiche d'identité de la fiche. 

Concernant l'affichage du nombre d'observation par année, étant donné que c'est un atlas pour tout public, attention à ce que cela ne laisse pas penser que l'espèce est en augmentation ou diminution, alors qu'on se base sur du contact avec tout ce que cela a d'aléatoire et irrégulier.

**Comment by mathieubossaert** [comment]
Ah oui bien. Je n'avais pas été attentif à ça. 


Mathieu BOSSAERT 
-- 
Responsable du système d'information (http://si.cenlr.org) 
ligne directe : 04 67 29 90 65 

Membre de la Fédération des Conservatoires d'espaces naturels www.reseau-cen.org 
Venir nous voir 
Immeuble le Thèbes - 26 Allées de Mycènes - 34000 Montpellier 

----- Mail original -----

De: "Camille Monchicourt" <notifications@github.com> 
À: "PnEcrins/GeoNature-atlas" <GeoNature-atlas@noreply.github.com> 
Cc: "mathieubossaert" <mathieu.bossaert@cenlr.org>, "Comment" <comment@noreply.github.com> 
Envoyé: Lundi 27 Juin 2016 16:09:16 
Objet: Re: [PnEcrins/GeoNature-atlas] Champs pour chaque taxon (#5) 


Oui en effet. Actuellement cette info est déjà présente avec le petit curseur présent sur la carte qui commence à l'année de la première observation mais on pourrait aussi mettre plus en évidence cette info en la mentionnant dans la fiche d'identité de la fiche. 
Concernant l'affichage du nombre d'observation par année, étant donné que c'est un atlas pour tout public, attention à ce que cela ne laisse pas penser que l'espèce est en augmentation ou diminution, alors qu'on se base sur du contact avec tout ce que cela a d'aléatoire et irrégulier.

**Comment by camillemonchicourt** [comment]
Oui c'est bien ça, aujourd'hui cela sert à filtrer la carte mais pas à afficher clairement l'année de première observation. :-)
