### ISSUE TITLE
Petite erreur dans la doc d'installation - vX.Y.Z.zip

### ISSUE THREAD

**Issue by TomMilon** [PnEcrins/GeoNature-atlas#57]
Bonjour!
C'est pas grand chose, mais j'ai remarqué que les lignes de commandes concernant la récupération la dernière version (X.Y.Z), par rapport à la nomenclature de vos release, il manque un v : 
```
wget https://github.com/PnEcrins/GeoNature-atlas/archive/vX.Y.Z.zip
unzip vX.Y.Z.zip
```
Voilou
Test de l'installation en cours
Bonne journée

**Comment by camillemonchicourt** [comment]
Bien vu, merci ! Et merci pour les tests car on n'a pas encore pu en faire beaucoup !
Et l'aspect avec ou sans GeoNature est bien compliqué à packager et rendre simple. 
Chacun devant adapter `atlas.vm_observations` à son contexte et devant mettre en place une stratégie pour accéder à sa BDD source (en dupliquant ses données sources dans l'atlas ou en y accédant en lecture avec un FDW, en s'inspirant de ce qu'on a fait avec GeoNature). 

N'hésite pas pour d'autres retours et je suis intéressé pour qu'on en rediscute.

**Comment by TomMilon** [comment]
Je te tiens au jus (j'espère arriver à tester ça en 1heure, 2 max - défis!)

**Comment by TomMilon** [comment]
Autre idées d'ajout dans la doc : 
pour tester l'outil avec des données test =
mv /home/MONUSER/atlas/data/ref/communes.shp.sample /home/MONUSER/atlas/data/ref/mescommunes.shp
mv /home/MONUSER/atlas/data/ref/emprise_territoire.sample.shp /home/MONUSER/atlas/data/ref/emprise_territoire.shp
