### ISSUE TITLE
Installation : adaptation de atlas.sql ou installation de Taxhub?

### ISSUE THREAD

**Issue by TomMilon** [PnEcrins/GeoNature-atlas#58]
Ne trouvant pas directement comment installer TaxHub (pas trouvé de doc d'install), je me suis dis que j'utiliserai directement les tables de taxref que j'ai en base.

Cependant, dans le fichier data/atlas.sql, la requête est SELECT * FROM taxonomie.taxref;

D'où deux questions : 

- Existe-t-il une doc pour installer TaxHub?
- Sinon, quels sont les champs nécessaire pour construire atlas.vm_taxref?

**Comment by TheoLechemia** [comment]
Salut,

Pour la doc de TaxHub, il me semble que Gil est en train de travailler dessus.
Sinon la vm_taxref est une simple copie de la table taxref du MNHN, voici la liste des champs:

  

-   taxref.cd_nom,
-     taxref.id_statut,
-     taxref.id_habitat,
-     taxref.id_rang,
-     taxref.regne,
-     taxref.phylum,
-     taxref.classe,
-     taxref.ordre,
-     taxref.famille,
-     taxref.cd_taxsup,
-     taxref.cd_ref,
-     taxref.lb_nom,
-     taxref.lb_auteur,
-     taxref.nom_complet,
-     taxref.nom_valide,
-     taxref.nom_vern,
-     taxref.nom_vern_eng,
-     taxref.group1_inpn,
-     taxref.group2_inpn,
-     taxref.nom_complet_html,
-     taxref.cd_sup

**Comment by TomMilon** [comment]
Merci :)

**Comment by camillemonchicourt** [comment]
L'installation de TaxHub est pas tout à fait fini, on y bossé en ce moment.
Mais lors de l'installation automatique de la BDD de l'atlas si tu mets install_taxonomie à true, il t'installe tout le schéma Taxonomie de taxhub dans la BDD de l'atlas
