### ISSUE TITLE
Utilisation de vues non matérialisées

### ISSUE THREAD

**Issue by TomMilon** [PnEcrins/GeoNature-atlas#59]
Bonjour,
Savez-vous s'il est possible d'utiliser GeoNature-atlas avec des vues non matérialisés (même si du coup, cela est moins intéressant)?
En effet, je travaille avec Postgresql 9.1... (désolé ^^)

**Comment by TheoLechemia** [comment]
Sur le papier, il n'y a pas de raison que ça ne marche pas.
Mais vu le temps de calcul de certaines VM (notamment vm_observations, et vm_observations_maille qui mettent plusieurs minutes), je ne pense pas que ce soit viable.

**Comment by TomMilon** [comment]
OK merci

**Comment by camillemonchicourt** [comment]
Oui pour des tests c'est possible mais en effet ça sera long. Sinon il est possible d'en faire des tables en gardant les mêmes noms.
