### ISSUE TITLE
Fichiers "exemple" pour tester l'installation

### ISSUE THREAD

**Issue by TomMilon** [PnEcrins/GeoNature-atlas#60]
Bonjour,

J'ai testé l'installation avec les données présentes dans le dossier data/ref en changeant le nom des fichiers : 
````
mv /home/MONUSER/atlas/data/ref/communes.shp.sample /home/MONUSER/atlas/data/ref/mescommunes.shp
mv /home/MONUSER/atlas/data/ref/emprise_territoire.sample.shp /home/MONUSER/atlas/data/ref/emprise_territoire.shp
````

et, effectivement, ça ne fonctionne pas : 
``Unable to open datasource XXX with the following drivers.``
Les fichiers ne sont pas complet.

Ça pourrait être top, pour tester l'installation, d'avoir un jeu test clé en main et prévoir le fichier de config sur ce jeu

**Comment by TheoLechemia** [comment]
Oui, les fichiers mis en .shp.sample sont en fait des fichiers vides. C'est simplement pour rappeler à l'utilisateur qu'il faut qu'il range ici ses shapefiles des communes et de son territoire. Il faut bien mettre le .shp, .dbf, .shx et .prj sinon en effet l'installation renvoie `Unable to open datasource XXX with the following drivers.`

Et en fait ces fichiers servent à créer la `vm_observations` notamment. On intersecte toutes les données d'observations avec l'emprise du territoire fourni par l'utilisateur (qui est mis en base dans la table `t_layer_territoire`) Du coup en fournissant ces shapefiles 'test', il faudrait également fournir une table des observations qui colle avec ce shapefile, sinon la vm_observations sera toujours vide...

Je ne sais pas si ça répond à ta question..

**Comment by TomMilon** [comment]
Ça répond tout à fait. J'ai eu tout a l'heure Camille au téléphone, on en a discuté rapidement. J'ai créé ce ticket pour garder l'idée de fichier "test" fonctionnel et directement disponible dans la config à l'installation.

C'est pas l'endroit, mais je n'ai le mail d'aucun d'entre vous (et je ne trouve pas la possibilité d'envoyer un message perso à travers Github). J'ai des soucis de droit d'accès (alternativement ``configuration error:  couldn't perform authentication. AuthType not set!:`` et ``client denied by server configuration: /home/xxx/atlas.wsgi``) et je dois avancé sur d'autres sujets aujourd'hui. Je mets donc le test de l'outil en standby et relance ça quand j'ai un peu de temps.

A plus

Thomas

**Comment by TheoLechemia** [comment]
ça marche ! Désolé pour les éventuels doublons, je ne suis plus au parc depuis la semaine dernière, mais je continue à suivre le projet ;)

pour mon mail: lechemia.theo AT gmail.com . Si tu as d'autres soucis, hésites pas

**Comment by camillemonchicourt** [comment]
Bien vu tout ça, du coup j'ai viré les 2 couches SAMPLE vides et mis des vrais SHP exemples, avec les communes du PNE et le TERRITOIRE du PNE (https://github.com/PnEcrins/GeoNature-atlas/commit/1828c5022c119aaa45b97f297dfaecbe79e8d023).
Du coup ça colle bien avec les tests, car, comme expliqué dans la doc, si on n'utilise pas GeoNature, une table de tests (`synthese.syntheseff`) avec 2 observations dans le PNE est intégrée.

**Comment by camillemonchicourt** [comment]
Du coup, tout ça est dispo dans la 1.1.2 qui vient de sortir - https://github.com/PnEcrins/GeoNature-atlas/releases
Ça devrait faciliter les tests, surtout en mettant `install_taxonomie=true` et `geonature_source=false` dans `settings.ini`.
J'ai repris aussi le `settings.ini.sample` en y intégrant les SHP de tests par défaut. 

J'ai un peu clarifié l'ordre des blocs dans l'installation aussi. 

Du coup tu devrais arriver à faire une installation rapidement en repartant au propre sur la 1.1.2 mais par contre c'est PostgreSQL 9.1 et son absence de vues matérialisées qui risque d'être un peu galère.

Pour tes autres erreurs, je ne sais pas trop à quoi c'est du. Peut-être qu'une nouvelle installation propre régleront le problème ?

**Comment by TomMilon** [comment]
Allez, c'est parti ;)

**Comment by TomMilon** [comment]
ça avance :).
Plus de problème d'accès (j'ai supprimé la ligne ``Require all granted``, suite à la lecture de ce [post ](http://stackoverflow.com/questions/21265191/apache-authtype-not-set-500-error)- pas sûr que ce soit une bonne idée, mais ça marche.

Je n'ai "plus que" des problème SQL maintenant => il faut que j'adapte data/atlas.sql pour qu'il soit cohérent avec mes données.

Par contre, si je comprends bien, il faut que les données soit déjà présente dans la même base que celle où j'installe geonature_atlas? Donc 
1/ Je créer la base manuellement, 
2/ je me fait un petit schema avec mes données et 
3/ je lance install_db.sh

C'est bien ça?

**Comment by camillemonchicourt** [comment]
OK, pour la conf Apache, c'est pas un domaine qu'on maitrise super bien.

Pour l'installation de la BDD, le script install_db.sh est global, il installe la BDD, les schémas etc. Si tu veux l'utiliser il ne faut pas avoir de BDD existante. Donc mieux vaut le laisser tout mettre en place, puis intégrer tes données et adapter les vues dans un second temps.

Si tu veux faire à la main, en commençant par créer la BDD et adapter les vues, il faudra alors installer le reste à la main étape par étape en s'inspirant du contenu du script automatique

**Comment by TomMilon** [comment]
OK, je n'avais pas vu que les tables étaient construites avec le script atlas_geonature.sql en fait

**Comment by camillemonchicourt** [comment]
Pas sur de comprendre, le fichier `atlas_geonature.sql` permet de faire les FDW vers la BDD source GeoNature, il n'est exécuté que si `geonature_source=true` donc dans ton cas, il n'est pas utile. 
Il peut par contre servir d'exemple si tu veux faire un FDW vers ta propre BDD source.

C'est dans le fichier `data/atlas.sql` que les tables et VM de l'atlas sont créées.

**Comment by TomMilon** [comment]
Effectivement, désolé, en voulant aller trop vite, je m’emmêle les pinceaux.
En fait, je pensais qu'il me manquait des tables, ce qui me généré des erreurs, En fait, je pense que c'est lié à une histoire de droit (ERROR:  permission denied for relation spatial_ref_sys)

Voici un bloc d'erreur dans log/install_db.log: 
ERROR:  permission denied for relation spatial_ref_sys
CONTEXT:  SQL statement "SELECT SRID         FROM spatial_ref_sys WHERE SRID = new_srid"
PL/pgSQL function "addgeometrycolumn" line 50 at SQL statement
SQL statement "SELECT AddGeometryColumn('',$1,$2,$3,$4,$5,$6,$7)"
PL/pgSQL function "addgeometrycolumn" line 5 at SQL statement
ERROR:  current transaction is aborted, commands ignored until end of transaction block
invalid command \.
ERROR:  syntax error at or near "aa"
LINE 1: aa + coeur 252608.74 2526.09 339.44 0106000020110F0000010000...
        ^
ROLLBACK
ERROR:  relation "atlas.t_layer_territoire" does not exist

**Comment by camillemonchicourt** [comment]
Il semble en effet qu'il y ait un problème de droits sur `public.spatial_ref_sys` mais là c'est du à ton PostgreSQL et plus l'atlas.

Je relance une installation test ici pour voir ce que ça donne.

**Comment by camillemonchicourt** [comment]
Je viens de refaire une installation complète en repartant sur une installation complète de la BDD et tout passe nickel - http://92.222.107.92/atlas/

J'étais en mode test donc avec : 
- install_taxonomie=true
- geonature_source=false
- communes_shp=/home/synthese/atlas/data/ref/communes-pne.shp
- limit_shp=/home/synthese/atlas/data/ref/territoire-pne.shp

Je vois juste que les 2 données exemple ne remontent pas car elles sont localisées sur les Cévennes :-)
Je vais corriger ça.

**Comment by camillemonchicourt** [comment]
Voila, les 2 données exemple remontent bien - http://92.222.107.92/atlas/

**Comment by camillemonchicourt** [comment]
Et concernant la configuration APACHE, tu avais raison, il y avait une coquille, j'ai corrigé la doc - https://github.com/PnEcrins/GeoNature-atlas/blob/master/docs/installation.rst#configuration-dapache
