### ISSUE TITLE
FICHE ESPECE - tous les taxons apparaissent comme protégés et patrimoniaux

### ISSUE THREAD

**Issue by gildeluermoz** [PnEcrins/GeoNature-atlas#63]
exemple pour les données PNE :  le rat noir, la taupe, la myrtille, ...etc ne sont ni patrimoniaux ni protégés

**Comment by camillemonchicourt** [comment]
Corrigé par https://github.com/PnEcrins/GeoNature-atlas/pull/71/commits/cf10e718ca103983a3aa5eb9bd4ae93871d946c2
