### ISSUE TITLE
Liste d'espèces, vignette et médias

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature-atlas#64]
On vient de voir que si un taxon a un media de type video, alors c'est ce média qu'il essaie d'afficher à la place de la vignette dans la liste des espèces (exemple : style="background-image:url(x38z5er))

C'est le taxon.path ici qui doit s’emmêler les pédales - https://github.com/PnEcrins/GeoNature-atlas/blob/master/templates/tabTaxons.html#L29

**Comment by camillemonchicourt** [comment]
Il semblerait que ce n'est que dans les listes d'especes des groupes : http://biodiversite.ecrins-parcnational.fr/groupe/Mammif%C3%A8res

Pas de soucis dans les listes d'un rang taxonomique : http://biodiversite.ecrins-parcnational.fr/liste/655482

**Comment by gildeluermoz** [comment]
en fait il affiche plusieurs fois le même taxon et à chaque ligne il affiche une image différente (ou un autre média si ce n'est pas une image). je pense que c'est un pb de distinct ou de group by dans le sql.
Je creuse

**Comment by gildeluermoz** [comment]
pb de filtrage des media sur le join avec vm_medias
