### ISSUE TITLE
Sécurité, injection SQL

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature-atlas#65]
Faire un tour de l'application

**Comment by gildeluermoz** [comment]
j'ai fait un tour vite fait.
D'abord, rien à voler d'important. Pas de données personnelles.  
Pas d'authentification donc pas de pass accessible. Les seules données éventuellement atteignables sont justement les données que l'on cherche à rendre publiques.
Le risque de corruption de la base n'est pas critique et la base peut-être remontée en qq minutes avec le script install_db.sh. La base elle même ne contient pas de données unique qui ne seraient pas stockée ailleurs.
Sinon :
Pas de formulaire où l'on saisi du texte envoyé au serveur
Les seules requêtes ajax qui interrogent la base sont passées à l'API via des routes préformatées gérées par SQL-ALCHEMY. Cet ORM présente des protections contre ce type d'attaque et les requêtes sont écrite en requêtes préparées.
Les autres requêtes sont gérées en interne par le serveur qui retourne une page complète (JINJA) (non accessible par le client)
Si malgré tout ça l'attaque réussi à injecter du sql, l'utilisateur qui accède à la base n'a que des droits en lecture avec un simple GRANT SELECT ON TABLE...
Voilà pour le tour du sujet. Je pense qu'on peut clore le sujet !

**Comment by camillemonchicourt** [comment]
OK en effet. C'est une analyse complète. Merci
