### ISSUE TITLE
Supprimer branche RELATIV ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature-atlas#68]
Cette branche avait servi à passer le projet en chemin relatif et c'est fonctionnel mais elle a toujours 5 commits qui n'ont pas été mergé. 
Voir https://github.com/PnEcrins/GeoNature-atlas/tree/relativ
Du coup @TheoLechemia est-ce qu'on peut la suppriemr ou il y a des choses à intégrer parmi ces 5 commits ?

**Comment by TheoLechemia** [comment]
Oui la branche master est à jour vous pouvez supprimer "relativ"

**Comment by camillemonchicourt** [comment]
OK merci, c'est fait.
