### ISSUE TITLE
Bug recherche dans Galerie photos

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature-atlas#75]
Je viens de constater un nouveau bug dans la galerie photos.
Pas de changement récemment dans la page hormis l'intégration des liens vers les FICHES ESPECES dans le slideshow. 

La recherche ne filtre pas et la console indique cette erreur : 

`galleryPhoto.js:148 Uncaught TypeError: Cannot read property 'toLowerCase' of null(…)`

**Comment by gildeluermoz** [comment]
fix with 23030362391ddae38b8143a565b272e684dceba0
