### ISSUE TITLE
Legende des cartes ne se ferme pas

### ISSUE THREAD

**Issue by TheoLechemia** [PnEcrins/GeoNature-atlas#76]
Quand on reclique sur le bouton légende, elle ne se ferme pas.
La console affiche `legend.removeFrom is not a function`
C'est surement dû au passage à leaflet 1.0
![legende](https://cloud.githubusercontent.com/assets/15265745/20523233/70c9ac32-b08a-11e6-88ce-40dd556ef0a4.PNG)

**Comment by camillemonchicourt** [comment]
Ouais bizarre car cette fonction est toujours dans leur doc : http://leafletjs.com/reference.html#icontrol-onremove

Je creuse...

**Comment by camillemonchicourt** [comment]
Pardon, le lien vers la bonne doc est http://leafletjs.com/reference-1.0.2.html#layer-removefrom
