### ISSUE TITLE
FICHE ESPECES - Chargement carte et sablier

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature-atlas#77]
Le sablier ne reste plus affiché tout le temps du chargement des données...
Ça fonctionnait initialement.

**Comment by TheoLechemia** [comment]
Je l'avais fait à la main, et avec un svg (le navigateur affichait d'ailleurs que ce ne serait bientôt plus supporté).
Pour pas réinventer la roue, il y a ça : https://github.com/makinacorpus/Leaflet.Spin

**Comment by TheoLechemia** [comment]
J'ai re-regardé. Quand tu zoom sur la carte avant que les données soient chargées, on voit le sablier qui apparait derrière les tuiles.
C'est juste un problème de z-index je pense.
