### ISSUE TITLE
FICHE TAXON - distinguer les données anciennes et les données récentes

### ISSUE THREAD

**Issue by gildeluermoz** [PnEcrins/GeoNature-atlas#8]

**Comment by TheoLechemia** [comment]
A faire: rajouter une légende et passer dans custom.js les classes de dates

**Comment by camillemonchicourt** [comment]
On peut même aller plus loin dans la customisation du fonctionnement : 
- paramètre pour le seuil du nombre d'années
- couleur des marqueurs
- seuil de zoom auquel on desactive les clusters
- voire plus compliqué si on desactive la distinction par ancienneté

**Comment by camillemonchicourt** [comment]
Le développement a été fait et fonctionne bien - https://github.com/PnEcrins/GeoNature-atlas/commit/c45207b85a085008e18307c28da3e468a602a608
Restait plus qu'à rendre certains éléments paramétrables. 

![anciennete](https://cloud.githubusercontent.com/assets/4418840/16071616/960e0884-32dc-11e6-87d4-934222bc9410.jpg)

Néanmoins on se rend compte que ce système n'est pas forcément le plus intuitif pour les utilisateurs, qu'il nécessite une légende, et est peu souple. 

Nous avons une habitude de dissocier moins de 10 ans, mais il y a peu de chance que cela soit ce qui intéresse le visiteur. 

De plus quand plusieurs observations se superposent, on n'arrive pas à savoir si il y en a 2 ou 40.

Du coup l'idée est de mettre en place un slider sous la carte allant de 1973 à l'année en cours et de permettre à l'utilisateur de jouer sur la période à afficher. 

En s'inspirant de ce qui a été fait ici avec l'altitude - http://phenoclim.org/fr/communaute/phenologie/carte-vegetaux et dont le code source (Python Django) est ici - https://github.com/makinacorpus/phenology-backend/tree/master/phenology

**Comment by camillemonchicourt** [comment]
Voila le premier résultat : 

![01](https://cloud.githubusercontent.com/assets/4418840/16120699/c2748416-33e0-11e6-9608-cb508a85b983.jpg)

![02](https://cloud.githubusercontent.com/assets/4418840/16120701/c4becfc4-33e0-11e6-8ac6-bada25ca74bb.jpg)

![03](https://cloud.githubusercontent.com/assets/4418840/16120702/c678f9ca-33e0-11e6-974a-df2b4246c70b.jpg)

![04](https://cloud.githubusercontent.com/assets/4418840/16120706/c8a3ecd2-33e0-11e6-8dd3-cf5c1975bea6.jpg)

![05](https://cloud.githubusercontent.com/assets/4418840/16120707/cac709ea-33e0-11e6-80ac-e19aca5a6061.jpg)

**Comment by camillemonchicourt** [comment]
Dans les exemples ci-dessus, la borne minimum (1973) est un paramètre fixe - https://github.com/PnEcrins/GeoNature-atlas/commit/33fb197015b3d2dfd70034ab4e407a3169eb5f20#diff-3aecf28686328509793e65e5bfca3db1R25
La borne maximum est l'année en cours. 

Cependant, si il y a des observations avant 1973, cela pose problème (https://github.com/PnEcrins/GeoNature-atlas/issues/16#issuecomment-226712041).

De plus si la première observation date de 1995, c'est dommage de faire commencer la slider en 1973...

Du coup on investigue un moyen de calculer l'année min et max de manière dynamique pour chaque taxon. 

Mais du coup il devient compliqué d'afficher les bornes intermédiaires tous les 10 ans car si on démarre en 1940, elles se superposent...

![slider](https://cloud.githubusercontent.com/assets/4418840/16145334/48e6e056-3478-11e6-815a-6c22496c4211.jpg)

A voir si on fait moins de classes quand la période dépasse 50 ans.
Ou si on adapte la longueur du slider en fonction de la période.
Ou si le slider fait toujours 100% de la largeur de la carte et c'est la longueur des seuils qui varie...

A voir selon la maquette finale.

**Comment by camillemonchicourt** [comment]
Si on change la largeur du slider en surcouchant la classe ``slider-horizontal`` alors les labels ne sont plus en face des points. 

![slider-width](https://cloud.githubusercontent.com/assets/4418840/16145898/8f21559e-347b-11e6-9ae6-6a8c5f03b036.jpg)

Il semble y avoir depuis peu la possibilité de définir la largeur dans ``src/sass/_variables.scss`` (https://github.com/seiyria/bootstrap-slider/pull/579/files) mais ensuite à voir comment cela s'applique et si ça modifie bien les labels pour qu'ils soient positionnés en face des points comme demandé ici - https://github.com/seiyria/bootstrap-slider/issues/566. 

Par contre, si la largeur du slider est fluide en fonction de la taille d'écran, les labels bougent selon la lergeur du slider - https://github.com/seiyria/bootstrap-slider/issues/341

**Comment by camillemonchicourt** [comment]
Solution actuelle, faire sauter les seuils : 

![seuils](https://cloud.githubusercontent.com/assets/4418840/16147550/f9de8d7c-3483-11e6-930f-cdc95aac4032.jpg)

Commit - https://github.com/PnEcrins/GeoNature-atlas/commit/2327e4c5fd8869f0da7d6a3cc97c48a5582ad8bf

**Comment by gildeluermoz** [comment]
On peut considérer que le sujet est traité avec le slider
