### ISSUE TITLE
FICHE COMMUNES - mailles vides à l'ouverture

### ISSUE THREAD

**Issue by gildeluermoz** [PnEcrins/GeoNature-atlas#80]
Seulement à l'ouverture de la page, les mailles sur la carte sont vides avec un contour rouge. Si on clique sur la ligne d'un taxon, le fonctionnement attendu est rétabli

**Comment by gildeluermoz** [comment]
Camille, c'est pas la correction avec le z-index qui est en cause ?

**Comment by camillemonchicourt** [comment]
C'est pas un bug. Les mailles vides se sont les 100 dernieres observations sur la commune (idem sur la page d'accueil). C'est différent du nombre d'observation d'une espece. 
A rcreuser si ce n'est pas clair ?
