### ISSUE TITLE
Liste d'especes / Pagination et tooltip

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature-atlas#81]
Sur les listes d'especes (fiches communes, fiches rand, fiche groupe), quand on passe en page 2 ou plus, les tooltip dans la liste ne fonctionnent plus. Ceux de la sidebar fonctionnent toujours par contre.

Idem quand on trie, les éléments des pages 2 et plus n'ont pas leur tooltip qui fonctionnent.

**Comment by gildeluermoz** [comment]
Fix with eac548c8159a0672238e608620791e3cc08e49ae

**Comment by camillemonchicourt** [comment]
Je vois toujours le problème.
Il est réglé si on clique une fois mais pas sans ça.

**Comment by gildeluermoz** [comment]
Fix with eac548c pour le moment c'est dans le develop.
