### ISSUE TITLE
Absence champs "diffusable" dans syntheseff atlas

### ISSUE THREAD

**Issue by DonovanMaillard** [PnEcrins/GeoNature-atlas#98]
Petit bug constaté à l'instant, 

Dans la table `synthese.syntheseff`, il y a bien un champ `diffusable` oui/non pour permettre de sélectionner les données à renvoyer sur l'atlas. 

Dans la table distante `atlas.syntheseff`, ce champ n'existe pas ;)

**Comment by camillemonchicourt** [comment]
Oooops, oubli. 
Mais c'est tout à fait ça. 

Le champs est bien dans la table `synthese.syntheseff` de GeoNature mais pas dans sa fille `synthese.syntheseff` de GeoNature-atlas.

C'est aussi à prendre en compte dans le `where` de `atlas.vm_observations`.

**Comment by DonovanMaillard** [comment]
ouaip, par défaut on est encore sur les données parc.... qui reste dans usershub à l'install et donc avec 0 données pour les organismes qui déploient en principe (sauf pour flavia...)

**Comment by camillemonchicourt** [comment]
C'est maintenant corrigé dans le MASTER (https://github.com/PnEcrins/GeoNature-atlas/pull/102/files) donc ça sera disponible dans la prochaine version et pour les instances existantes, il faudra mettre à jour la BDD de GeoNature-atlas.

**Comment by gildeluermoz** [comment]
À priori si la donnée n'est pas diffusable, elle ne doit pas être dans l'Atlas. Donc ce champ est inutile dans l'Atlas.
La requête de constitution devrait exclure ces données.

**Comment by camillemonchicourt** [comment]
Hum bah si dans la table syntheseff en FDW il faut ce champs pour ensuite pouvoir faire le where dans vm_observations.
C'est ce que j'ai fait dans le commit indiqué.
