### ISSUE TITLE
Config.py - Sélection des taxons à trier dans les blocs photos

### ISSUE THREAD

**Issue by DonovanMaillard** [PnEcrins/GeoNature-atlas#99]
Un bug constaté sur le tri des taxons à choisir pour les blocs photo...

Nous voulions, pour flavia avoir un bloc papillons de jour, un bloc "macro papillons de nuit" et un bloc "micro papillons de nuit"... ces groupes n'existent pas tel quel dans le taxref, on doit donc faire la sélection sur les familles. 

Cette requête fonctionne : (plus court et incomplète)
AFFICHAGE_RANG_STAT = True
COLONNES_RANG_STAT = 3
RANG_STAT = [{'famille': ["Hesperiidae", "Lycaenidae", "Nymphalidae", "Papilionidae", "Pieridae", "Riodinidae", "Zygaenidae"]}, {'famille': ["Brahmaeidae", "Cossidae"]}, {'famille': ["Adelidae","Alucitidae","Argyresthiidae","Autostichidae"]}] 
RANG_STAT_FR = ['Rhopalocères & Zygènes', 'Macro-hétérocères', 'Micro-hétérocères']

Mais pas celle-ci, qui est plus longue... mais complète (ne vous étouffez pas tout de suite, on a besoin de vous pour régler le bug ;) )
AFFICHAGE_RANG_STAT = True
COLONNES_RANG_STAT = 3
RANG_STAT = [{'famille': ["Hesperiidae", "Lycaenidae", "Nymphalidae", "Papilionidae", "Pieridae", "Riodinidae", "Zygaenidae"]}, {'famille': ["Brahmaeidae", "Cossidae", "Drepanidae", "Erebidae", "Geometridae", "Hepialidae", "Lasiocampidae", "Limacodidae", "Noctuidae", "Nolidae", "Notodontidae", "Saturniidae","Sphingidae"]}, {'famille': ["Adelidae","Alucitidae","Argyresthiidae","Autostichidae","Bedelliidae","Blastobasidae","Bucculatrigidae","Chimabachidae","Choreutidae","Cimeliidae","Coleophoridae","Cosmopterigidae","Crambidae","Douglasiidae","Elachistidae","Endromidae","Epermeniidae","Eriocraniidae","Euteliidae",￼"Gelechiidae","Glyphipterigidae","Gracillariidae","Heterogynidae","Incurvariidae","Lecithoceridae","Lyonetiidae","Lypusidae","Micropterigidae","Momphidae","Nepticulidae","Oecophoridae","Plutellidae","Prodoxidae","Psychidae","Pterolonchidae","Pterophoridae","Pyralidae","Schreckensteiniidae","Scythrididae","Sesiidae","Stathmopodidae","Thyrididae","Tineidae","Tischeriidae","Tortricidae","Yponomeutidae","Ypsolophidae"]}] 
RANG_STAT_FR = ['Rhopalocères et Zygènes', 'Macro-hétérocères', 'Micro-hétérocères']

Merci d'avance!

**Comment by DonovanMaillard** [comment]
petite précision.... pas de bug de "" dans la saisie, vérifié sur sublime text ;)... par contre pour les virgules, ca sent la connerie possible ;)

**Comment by TheoLechemia** [comment]
Tu vas devenir un expert en programmation Donovan ;)

T'as un caractère bizarre après 'Euteliidae', du coup ça fait une erreur de
synthaxe.
Essaye avec ça:

RANG_STAT = [{'famille': ["Hesperiidae", "Lycaenidae", "Nymphalidae",
"Papilionidae", "Pieridae", "Riodinidae", "Zygaenidae"]},
 {'famille': ["Brahmaeidae", "Cossidae", "Drepanidae", "Erebidae",
"Geometridae", "Hepialidae", "Lasiocampidae", "Limacodidae", "Noctuidae",
"Nolidae", "Notodontidae", "Saturniidae","Sphingidae"]},
  {'famille':
["Adelidae","Alucitidae","Argyresthiidae","Autostichidae","Bedelliidae","Blastobasidae","Bucculatrigidae","Chimabachidae","Choreutidae","Cimeliidae","Coleophoridae","Cosmopterigidae","Crambidae","Douglasiidae","Elachistidae","Endromidae","Epermeniidae","Eriocraniidae","Euteliidae","Gelechiidae","Glyphipterigidae","Gracillariidae","Heterogynidae","Incurvariidae","Lecithoceridae","Lyonetiidae","Lypusidae","Micropterigidae","Momphidae","Nepticulidae","Oecophoridae","Plutellidae","Prodoxidae","Psychidae","Pterolonchidae","Pterophoridae","Pyralidae","Schreckensteiniidae","Scythrididae","Sesiidae","Stathmopodidae","Thyrididae","Tineidae","Tischeriidae","Tortricidae","Yponomeutidae","Ypsolophidae"]}]
RANG_STAT_FR = ['Rhopalocères et Zygènes', 'Macro-hétérocères',
'Micro-hétérocères']

Le ven. 20 janv. 2017 à 05:11, DonovanMaillard <notifications@github.com> a
écrit :

**Comment by camillemonchicourt** [comment]
Bien vu Théo, il avait bien une erreur dans la liste. Pas de bug donc ! :-)
